import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Derya Emlak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body>
          {children} 
      </body>
    </html>
  )
}
