import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";

export const metadata: Metadata = {
  title: "Derya Emlak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body>
          <ReduxProvider>{children}</ReduxProvider> 
      </body>
    </html>
  )
}
