import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "../components/public/theme-provider"

export const metadata: Metadata = {
  title: "Derya Emlak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>{children}</ReduxProvider>
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  )
}
